### ISSUE TITLE
Reproduction of results

### ISSUE THREAD

**Issue by zyz1002** [zbf1991/WeCLIP#4]
Hello, author.This is an excellent work!!!!
but I followed  instructions and the final segmentation result of mIoU was 73.5% on the VOC val. and mIou was not the same as your paper.(seg 74.9%)) on the VOC val. I don't know where the problem is.
this is my train log
[voc_train.log](https://github.com/user-attachments/files/15981308/voc_train.log)
Can you help me find the possible cause of the problem？
thanks!!!!

**Comment by kalpa61** [comment]
@zyz1002 Hello, may I ask if the result of running on the COCO dataset is 47.1%? My result is only 45.1%. I don't know where the problem lies.

**Comment by zbf1991** [comment]
> Hello, author.This is an excellent work!!!! but I followed instructions and the final segmentation result of mIoU was 73.5% on the VOC val. and mIou was not the same as your paper.(seg 74.9%)) on the VOC val. I don't know where the problem is. this is my train log [voc_train.log](https://github.com/user-attachments/files/15981308/voc_train.log) Can you help me find the possible cause of the problem？ thanks!!!!

hello, do you run the test_msc_flip.py to generate the result or you just see the result in the voc_train.log?

**Comment by zbf1991** [comment]
> @zyz1002 Hello, may I ask if the result of running on the COCO dataset is 47.1%? My result is only 45.1%. I don't know where the problem lies.

Hello, 47.1 is generated with CRF, and 45.1 seems like a low performance, I tested many times, and my final results are very stable, I am not sure what the reason is. Which GPU do you use? and which Cuda version?

**Comment by zbf1991** [comment]
Note that CRF was commented in "test_msc_flip_voc.py" and "test_msc_flip_coco.py". Please uncomment it!

**Comment by kalpa61** [comment]
The gpu I used is 4060ti16g and cuda version is 11.1. I got this by running test_msc_flip_voc.py according to the steps of the readme file. After I cancelled the CRF comment, the program reported an error, and the error message was as follows:

> 100%|===========================================================| 1449/1449 [12:14<00:00,  1.97it/s]
cams score:
{'pAcc': 0.9311450185340081, 'mAcc': 0.8652301888838562, 'miou': 0.7450621941332836, 'iou': {0: 0.9182371915398202, 1: 0.8444199267161099, 2: 0.4281354901728207, 3: 0.8765997857169765, 4: 0.6995592690876541, 5: 0.603404645228538
8, 6: 0.8660484587830951, 7: 0.7726234270967866, 8: 0.9023514801253747, 9: 0.4803293059419903, 10: 0.872614285348258, 11: 0.6315921639787885, 12: 0.8848607399731794, 13: 0.8784349152673446, 14: 0.7583784837935938, 15: 0.71880388
53909405, 16: 0.5506199802365973, 17: 0.9084501993319251, 18: 0.6842124700143497, 19: 0.8383188022864348, 20: 0.5283111707683739}}
segs score:
{'pAcc': 0.9286886147589374, 'mAcc': 0.8568004338766813, 'miou': 0.7261773252646428, 'iou': {0: 0.9185320625481816, 1: 0.8422162431826512, 2: 0.40926325511398864, 3: 0.8656251720079647, 4: 0.7027931923808766, 5: 0.67342392305806
96, 6: 0.8476416084125394, 7: 0.8138449246793811, 8: 0.881044747099725, 9: 0.35716750373806694, 10: 0.8580816602479282, 11: 0.5601474400931011, 12: 0.8702571474338304, 13: 0.8157707068207214, 14: 0.7570540386009106, 15: 0.765864
2517342461, 16: 0.5849994778423407, 17: 0.8404009903756583, 18: 0.5202677427277896, 19: 0.8013952545567103, 20: 0.5639324879028187}}
msc segs score:
{'pAcc': 0.9327187575444279, 'mAcc': 0.868885541798169, 'miou': 0.739377630610907, 'iou': {0: 0.9223887457021683, 1: 0.8266770062333169, 2: 0.3996768025855793, 3: 0.869336743011438, 4: 0.7135961787584352, 5: 0.6957818589643611, 
6: 0.8557282229761176, 7: 0.8200114623490995, 8: 0.8899294533564065, 9: 0.38923728478085035, 10: 0.8690920557605745, 11: 0.5807305147233682, 12: 0.8786044993477641, 13: 0.8299973237941765, 14: 0.7586400880594927, 15: 0.777833007
8023374, 16: 0.6095055603884043, 17: 0.8776243874724131, 18: 0.555614034770142, 19: 0.814349847686722, 20: 0.5925751643058783}}
crf post-processing...
[Parallel(n_jobs=12)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done 145 out of 1449 | elapsed:    0.4s remaining:    4.3s
[Parallel(n_jobs=12)]: Done 290 out of 1449 | elapsed:    0.4s remaining:    1.9s
[Parallel(n_jobs=12)]: Done 435 out of 1449 | elapsed:    0.4s remaining:    1.1s
[Parallel(n_jobs=12)]: Done 580 out of 1449 | elapsed:    0.4s remaining:    0.6s
[Parallel(n_jobs=12)]: Done 725 out of 1449 | elapsed:    0.4s remaining:    0.4s
[Parallel(n_jobs=12)]: Done 870 out of 1449 | elapsed:    0.4s remaining:    0.2s
[Parallel(n_jobs=12)]: Done 1015 out of 1449 | elapsed:    0.4s remaining:    0.1s
[Parallel(n_jobs=12)]: Done 1160 out of 1449 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=12)]: Done 1305 out of 1449 | elapsed:    0.4s remaining:    0.0s
错误: 没有找到进程 "20368"。
错误: 没有找到进程 "13548"。
错误: 没有找到进程 "7596"。
错误: 没有找到进程 "17316"。
错误: 没有找到进程 "25296"。
错误: 没有找到进程 "25064"。
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\Anaconda3\envs\wssam\lib\site-packages\joblib\externals\loky\process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "D:\Anaconda3\envs\wssam\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "D:\PycharmProject\WeCLIP\utils\dcrf.py", line 5, in <module>
    import torch.nn.functional as F
  File "D:\Anaconda3\envs\wssam\lib\site-packages\torch\__init__.py", line 605, in <module>
    _C._initExtension(manager_path())
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_msc_flip_voc.py", line 232, in <module>
    main(cfg=cfg)
  File "test_msc_flip_voc.py", line 213, in main
    crf_proc(config=cfg)
  File "test_msc_flip_voc.py", line 165, in crf_proc
    results = joblib.Parallel(n_jobs=n_jobs, verbose=10, pre_dispatch="all")([joblib.delayed(_job)(i) for i in range(len(name_list))])
  File "D:\Anaconda3\envs\wssam\lib\site-packages\joblib\parallel.py", line 1098, in __call__
    self.retrieve()
  File "D:\Anaconda3\envs\wssam\lib\site-packages\joblib\parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "D:\Anaconda3\envs\wssam\lib\site-packages\joblib\_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "D:\Anaconda3\envs\wssam\lib\concurrent\futures\_base.py", line 444, in result
    return self.__get_result()
  File "D:\Anaconda3\envs\wssam\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

**Comment by zyz1002** [comment]
> > Hello, author.This is an excellent work!!!! but I followed instructions and the final segmentation result of mIoU was 73.5% on the VOC val. and mIou was not the same as your paper.(seg 74.9%)) on the VOC val. I don't know where the problem is. this is my train log [voc_train.log](https://github.com/user-attachments/files/15981308/voc_train.log) Can you help me find the possible cause of the problem？ thanks!!!!
> 
> hello, do you run the test_msc_flip.py to generate the result or just see the result in the voc_train.log? Could u please run it again to see if the problem still exists?

thanks your reply!!  the results of test_msc_flip.py on VOC val without crf is 74.6%

**Comment by kalpa61** [comment]
我解决了这个问题，将test_msc_flip.py中的n_jobs = int(multiprocessing.cpu_count() * 0.8)改为n_jobs = int(multiprocessing.cpu_count() * 0.6)或其他较小的值，最后的结果是75.7%，感谢作者的回复

**Comment by jjxyhb** [comment]
> 您好，请问在 COCO 数据集上运行的结果是 47.1% 吗？我的结果只有 45.1%。我不知道问题出在哪里。

Hello, I would like to ask if you have obtained the segmentation results of the COCO dataset? How can I modify the test_msc_flip_seg.py file in the code to obtain the segmentation results of the coco dataset? Thank you
