### ISSUE TITLE
TerminatedWorkerError

### ISSUE THREAD

**Issue by kalpa61** [zbf1991/WeCLIP#6]
你好作者，我在取消CRF注释的情况下运行test_msc_flip_coco.py文件会报错，报错信息如下：
> [Parallel(n_jobs=3)]: Done 12040 out of 40137 | elapsed: 396.7min remaining: 925.8min
> [Parallel(n_jobs=3)]: Done 16054 out of 40137 | elapsed: 396.7min remaining: 595.2min
> [Parallel(n_jobs=3)]: Done 20068 out of 40137 | elapsed: 396.7min remaining: 396.8min
> [Parallel(n_jobs=3)]: Done 24082 out of 40137 | elapsed: 396.7min remaining: 264.5min
> [Parallel(n_jobs=3)]: Done 28096 out of 40137 | elapsed: 396.7min remaining: 170.0min
> [Parallel(n_jobs=3)]: Done 32110 out of 40137 | elapsed: 396.7min remaining: 99.2min
> [Parallel(n_jobs=3)]: Done 36124 out of 40137 | elapsed: 396.7min remaining: 44.1min
> 错误: 没有找到进程 "13492"。
> 错误: 没有找到进程 "1720"。
> 错误: 没有找到进程 "7832"。
> Traceback (most recent call last):
>   File "test_msc_flip_coco.py", line 244, in <module>
>     main(cfg=cfg)
>   File "test_msc_flip_coco.py", line 225, in main
>     crf_proc(config=cfg)
>   File "test_msc_flip_coco.py", line 177, in crf_proc
>     results = joblib.Parallel(n_jobs=n_jobs, verbose=10, pre_dispatch="all")([joblib.delayed(_job)(i) for i in range(len(name_list))])
>   File "D:\Anaconda3\envs\wssam\lib\site-packages\joblib\parallel.py", line 1098, in __call__
>     self.retrieve()
>   File "D:\Anaconda3\envs\wssam\lib\site-packages\joblib\parallel.py", line 975, in retrieve
>     self._output.extend(job.get(timeout=self.timeout))
>   File "D:\Anaconda3\envs\wssam\lib\site-packages\joblib\_parallel_backends.py", line 567, in wrap_future_result
>     return future.result(timeout=timeout)
>   File "D:\Anaconda3\envs\wssam\lib\concurrent\futures\_base.py", line 444, in result
>     return self.__get_result()
>   File "D:\Anaconda3\envs\wssam\lib\concurrent\futures\_base.py", line 389, in __get_result
>     raise self._exception
> joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.
即使我把n_jobs设置为3也不行，请问这该怎么解决呢，我的电脑配置为I5 12600、16G运行内存、4060Ti16G。

**Comment by zbf1991** [comment]
I think it maybe caused by low memory.  16g may not enough, I used a 64G memory workstation.

**Comment by kalpa61** [comment]
All right
