### ISSUE TITLE
Can not reach the results reported in the paper.

### ISSUE THREAD

**Issue by HYTHYThythyt** [zbf1991/WeCLIP#9]
Hi, author.
I use your codes and config for training in voc dataset, but it can not reach your results you reported in the paper(voc val: 74.9/76.4).
I had reproduced four times, the higest one is 73.3/74.4(crf).
I want to know is there any different config between yours and mine.
Some of my config are as follow, GPU: A6000, CUDA version: 11.4, OS: Ubuntu, Pytorch version: 1.9.0+cu111.
Thank you for your great job.

**Comment by HYTHYThythyt** [comment]
I had found the problem, thank for your great job again!

**Comment by zbf1991** [comment]
> Hi, author. I use your codes and config for training in voc dataset, but it can not reach your results you reported in the paper(voc val: 74.9/76.4). I had reproduced four times, the higest one is 73.3/74.4(crf). I want to know is there any different config between yours and mine. Some of my config are as follow, GPU: A6000, CUDA version: 11.4, OS: Ubuntu, Pytorch version: 1.9.0+cu111. Thank you for your great job.

Hello, do u use test_msc_voc.py to generate the final performance or u just see the result during train? 
My Config, GPU: 3090, Pytorch 1.12+cu11.3. I also use a 2080Ti with the same config, both of them can reach the performance.

**Comment by zbf1991** [comment]
> I had found the problem, thank for your great job again!

Ok GOOD LUCK!

**Comment by xd-429** [comment]
> I had found the problem, thank for your great job again!
The result of running the code is almost the same. What's your problem? How to solve it?

**Comment by jjxyhb** [comment]
> Hi, author. I use your codes and config for training in voc dataset, but it can not reach your results you reported in the paper(voc val: 74.9/76.4). I had reproduced four times, the higest one is 73.3/74.4(crf). I want to know is there any different config between yours and mine. Some of my config are as follow, GPU: A6000, CUDA version: 11.4, OS: Ubuntu, Pytorch version: 1.9.0+cu111. Thank you for your great job.

Hello, I would like to ask if you have obtained the segmentation results of the COCO dataset? How can I modify the test_msc_flip_seg.py file in the code to obtain the segmentation results of the coco dataset? Thank you
